import turtle as t
x = t.getscreen()
x.setup(800,800)
x.bgcolor("black")

# t.color("red")
# t.begin_fill()
# t.goto(100, 300)
# t.mainloop()
# t.end_fill()

# t.color("blue")
# t.begin_fill()
# t.goto(-200, -200)
# t.end_fill()

# t.color("pink")
# t.begin_fill()
# t.setposition(-200, -200)
# t.end_fill()

# t.color("green")
# t.begin_fill()
# t.setx(300)
# t.end_fill()

# t.color("pink")
# t.begin_fill()
# t.sety(300)
# t.end_fill()

# t.color("pink")
# t.begin_fill()
# t.setheading(90)
# t.end_fill()

# t.color("pink")
# t.begin_fill()
# t.seth(60)
# t.end_fill()

# t.color("pink")
# t.begin_fill()
# t.home()
# t.end_fill()

# t.color("pink")
# t.begin_fill()
# t.backward(100)
# t.speed(10)
# t.end_fill()

# t.color("pink")
# t.begin_fill()
# t.forward(100)
# print(t.xcor())
# t.end_fill()

# t.color("pink")
# t.begin_fill()
# t.forward(100)
# print(t.ycor())
# t.end_fill()

# t.color("pink")
# t.begin_fill()
# t.goto(200, 300)
# t.goto(100, 150)
# t.end_fill()

# t.color("pink")
# t.begin_fill()
# t.forward(100)
# t.undo()
# t.end_fill()

# t.color("green")
# t.begin_fill()
# t.title("My turtle")
# t.end_fill()

# t.color("red")
# t.begin_fill()
# t.pencolor("green")
# t.end_fill()

# t.color("green")
# t.begin_fill()
# t.setx(100)
# t.setposition(100, 100)
# t.goto(0, 100)
# t.sety(100)
# t.goto(0, 100)
# t.home()
# t.end_fill()

# t.color("red")
# t.begin_fill()
# t.circle(60)
# t.end_fill()

# t.color("pink")
# t.begin_fill()
# t.setx(200)
# t.setposition(100, 200)
# t.sety(200)
# t.setheading(200)
# t.goto(100, 200)
# t.home()
# t.end_fill()

# t.color("green")
# t.begin_fill()
# t.setx(100)
# t.setposition(100, 200)
# t.goto(0, 200)
# t.sety(100)
# t.goto(0, 100)
# t.home()
# t.end_fill()

# t.color("yellow")
# t.begin_fill()
# t.left(60)
# t.forward(100)
# t.right(120)
# t.backward(100)
# t.right(60)
# t.forward(100)
# t.right(120)
# t.backward(100)
# t.end_fill()

# t.color("green")
# t.begin_fill()
# t.forward(200)
# t.left(100)
# t.forward(210)
# t.right(100)
# t.backward(130)
# t.left(80)
# t.backward(205)
# t.end_fill()

# t.color("blue")
# t.begin_fill()
# t.forward(110)
# t.left(40)
# t.forward(100)
# t.left(50)
# t.forward(100)
# t.left(60)
# t.forward(100)
# t.right(150)
# t.backward(100)
# t.left(30)
# t.backward(100)
# t.left(60)
# t.backward(100)
# t.left(53)
# t.backward(100)
# t.end_fill()

# # t.color("pink")
# # t.begin_fill()
# # t.forward(50)
# # t.up()
# # t.forward(50)
# # t.down()
# # t.forward(50)
# # t.end_fill()

# # t.color("red")
# # t.begin_fill()
# # t.forward(100)
# # t.up()
# # t.isdown()
# # t.end_fill()

# t.color("yellow")
# t.penup() 
# t.sety(-150) 
# t.pendown() 
# t.circle(200) 
# t.penup() 
# t.sety(100) 
# t.setx(-50) 
# t.pendown() 
# t.dot(50) 
# t.penup() 
# t.setx(50) 
# t.pendown() 
# t.dot(50) 
# t.penup() 
# t.home() 
# t.sety(-30) 
# t.backward(60) 
# t.pendown() 
# t.width(4) 
# t.forward(150) 

# t.penup() 
# t.goto(300,300) 
# t.pendown() 
# t.write("Salom", 
#         move=True, 
#         font=("Verdana", 15, "normal")) 

# t.penup() 
# t.sety(280) 
# t.pendown() 
# t.write("Kamoljon", 
#         move=True, 
#         font=30) 

# t.penup() 
# t.sety(250) 
# t.pendown()
# t.forward(50)
# t.color("red")
# t.forward(50)

# t.penup() 
# t.goto(300,200) 
# t.pendown() 
# t.color('black') 
# t.forward(100) 
# t.color('red') 
# t.right(90) 
# t.forward(100) 
# t.color('blue') 
# t.right(90) 
# t.forward(100) 
# t.color('green') 
# t.right(90) 
# t.forward(100)

# t.color("black")
# t.penup()
# t.sety(0)
# t.setx(300)
# t.pendown()
# t.forward(50)
# t.pensize(10)
# t.forward(50)


# t.fillcolor("yellow")
# t.penup()
# t.sety(150)
# t.setx(600)
# t.pendown()
# t.begin_fill()
# t.circle(60)
# t.end_fill()

# t.color("yellow")
# t.penup()
# t.sety(10)
# t.setx(600)
# t.pendown()
# t.begin_fill()
# t.circle(60)
# t.end_fill()

# t.pencolor("purple")
# t.fillcolor("orange")
# t.pensize(10)
# t.speed(9)

# t.pen(pencolor = "purple", 
#       fillcolor = "orange",
#       pensize = 10,
#       speed = 9)

t.color("red")
t.penup()
t.sety(90)
t.pendown()
t.forward(70)
t.left(120)
t.forward(70)
t.right(60)
t.forward(-70)


t.mainloop()
