import turtle as t
x = t.getscreen()
x.setup(800,800)
x.bgcolor("black")

# t.color("pink")
# t.begin_fill()
# t.forward(50)
# t.up()
# t.forward(50)
# t.down()
# t.forward(50)
# t.end_fill()

                # *******************************************************************

# t.color("red")
# t.begin_fill()
# t.forward(100)
# t.up()
# t.isdown()
# t.end_fill()

                # ******************************************************************

# t.color("yellow")
# t.penup() 
# t.sety(-150) 
# t.pendown() 
# t.circle(200) 
# t.penup() 
# t.sety(100) 
# t.setx(-50) 
# t.pendown() 
# t.dot(50) 
# t.penup() 
# t.setx(50) 
# t.pendown() 
# t.dot(50) 
# t.penup() 
# t.home() 
# t.sety(-30) 
# t.backward(60) 
# t.pendown() 
# t.width(4) 
# t.forward(150) 

# t.penup() 
# t.goto(300,300) 
# t.pendown() 
# t.write("Salom", 
#         move=True, 
#         font=("Verdana", 15, "normal")) 

# t.penup() 
# t.sety(280) 
# t.pendown() 
# t.write("Kamoljon", 
#         move=True, 
#         font=30) 

# t.penup() 
# t.sety(250) 
# t.pendown()
# t.forward(50)
# t.color("red")
# t.forward(50)

# t.penup() 
# t.goto(300,200) 
# t.pendown() 
# t.color('grey') 
# t.forward(100) 
# t.color('red') 
# t.right(90) 
# t.forward(100) 
# t.color('blue') 
# t.right(90) 
# t.forward(100) 
# t.color('green') 
# t.right(90) 
# t.forward(100)

# t.color("grey")
# t.penup()
# t.sety(0)
# t.setx(300)
# t.pendown()
# t.forward(50)
# t.pensize(10)
# t.forward(50)


# t.fillcolor("yellow")
# t.penup()
# t.sety(150)
# t.setx(600)
# t.pendown()
# t.begin_fill()
# t.circle(60)
# t.end_fill()

# t.color("yellow")
# t.penup()
# t.sety(10)
# t.setx(600)
# t.pendown()
# t.begin_fill()
# t.circle(60)
# t.end_fill()

# t.pencolor("purple")
# t.fillcolor("orange")
# t.pensize(10)
# t.speed(9)

                # ****************************************************************

# t.pen(pencolor = "purple", 
#       fillcolor = "orange",
#       pensize = 10,
#       speed = 9)

# for i in range(15):
#     t.width(15-i)
#     t.forward(50+15+i)
#     t.right(90)

                # ****************************************************************

# t.color("green")
# t.penup()
# t.sety(120)
# t.setx(100)
# t.pendown()
# t.forward(100)
# t.right(140)
# t.forward(100)
# t.left(35)
# t.backward(100)
# t.right(140)
# t.backward(105)
# t.left(31)
# t.forward(110)

            #  ******************************************************************

# t.color("green")
# t.penup() 
# t.sety(100) 
# t.setx(-50) 
# t.pendown() 
# t.dot(30)

# t.penup() 
# t.sety(50) 
# t.setx(-50) 
# t.pendown() 
# t.dot(30)

# t.penup() 
# t.sety(0) 
# t.setx(-50) 
# t.pendown() 
# t.dot(30)

# t.penup() 
# t.sety(0) 
# t.setx(5) 
# t.pendown() 
# t.dot(30)

# t.penup() 
# t.sety(50) 
# t.setx(5) 
# t.pendown() 
# t.dot(30)

# t.penup() 
# t.sety(100) 
# t.setx(5) 
# t.pendown() 
# t.dot(30)

# t.penup() 
# t.sety(100) 
# t.setx(60) 
# t.pendown() 
# t.dot(30)

# t.penup() 
# t.sety(50) 
# t.setx(60) 
# t.pendown() 
# t.dot(30)

# t.penup() 
# t.sety(0) 
# t.setx(60) 
# t.pendown() 
# t.dot(30)

# t.color("grey")
# t.penup() 
# t.pensize(5)
# t.sety(140) 
# t.setx(-50) 
# t.pendown() 
# t.right(90)
# t.forward(140)
# t.left(90)
# t.forward(200)
# t.left(145)
# t.forward(240)

# t.penup()
# t.sety(0)
# t.setx(-50)
# t.pendown()
# t.left(77)
# t.backward(210)

#             # *********************************************************************
# t.color("grey")
# t.penup()
# t.sety(100)
# t.setx(50)
# t.pendown()
# t.forward(150)
# t.right(90)
# t.forward(150)
# t.right(90)
# t.forward(150)
# t.left(90)
# t.backward(150)

# t.penup()
# t.sety(80)
# t.setx(70)
# t.pendown()
# t.dot(10)

# t.penup()
# t.sety(25)
# t.setx(70)
# t.pendown()
# t.dot(10)

# t.penup()
# t.sety(-30)
# t.setx(70)
# t.pendown()
# t.dot(10)

# t.penup()
# t.sety(-30)
# t.setx(125)
# t.pendown()
# t.dot(10)

# t.penup()
# t.sety(25)
# t.setx(125)
# t.pendown()
# t.dot(10)

# t.penup()
# t.sety(80)
# t.setx(125)
# t.pendown()
# t.dot(10)

# t.penup()
# t.sety(80)
# t.setx(180)
# t.pendown()
# t.dot(10)

# t.penup()
# t.sety(25)
# t.setx(180)
# t.pendown()
# t.dot(10)

# t.penup()
# t.sety(-30)
# t.setx(180)
# t.pendown()
# t.dot(10)

            # *********************************************************************

# t.penup() 
# t.sety(100) 
# t.setx(-50) 
# t.pendown() 
# t.dot(50)

# t.penup() 
# t.sety(100) 
# t.setx(-50) 
# t.pendown() 
# t.dot(50)

# t.color("red")
# t.penup()
# t.sety(90)
# t.pendown()
# t.forward(70)
# t.left(120)
# t.forward(70)
# t.right(60)
# t.forward(-70)

# t.penup()
# t.sety(90)
# t.setx(35)
# t.pendown()
# t.backward(120)
# t.right(60)
# t.forward(120)
# t.left(120)
# t.forward(120)

# t.penup()
# t.sety(-15)
# t.setx(35)
# t.pendown()
# t.backward(250)
# t.right(120)
# t.backward(250)
# t.left(60)
# t.forward(250)

# t.penup()
# t.sety(-67)
# t.setx(200)
# t.pendown()
# t.forward(40)
# t.right(120)
# t.forward(40)
# t.left(60)
# t.backward(40)

# t.penup()
# t.sety(-67)
# t.setx(220)
# t.pendown()
# t.right(120)
# t.forward(70)
# t.right(60)
# t.backward(70)
# t.left(120)
# t.backward(70)

# t.penup()
# t.sety(-130)
# t.setx(222)
# t.pendown()
# t.forward(118)
# t.right(120)
# t.forward(120)
# t.left(60)
# t.backward(120)

# t.begin_fill()
# t.penup()
# t.sety(-102)
# t.setx(322)
# t.pendown()
# t.forward(30)
# t.left(120)
# t.forward(30)
# t.right(60)
# t.backward(30)

# t.begin_fill()
# t.penup()
# t.sety(-128)
# t.setx(322)
# t.pendown()
# t.forward(40)
# t.right(120)
# t.forward(40)
# t.left(60)
# t.backward(40)

# t.begin_fill()
# t.penup()
# t.sety(-163)
# t.setx(322)
# t.pendown()
# t.forward(80)
# t.left(120)
# t.forward(80)
# t.right(60)
# t.backward(80)

t.mainloop()
